import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { Invoice, InvoiceClient } from "./invoice-types";
import { formatCurrency, formatDate, calculateTotalCharges, calculateTotalPayments, calculateBalanceDue } from "./invoice-utils";

const PURPLE = "#7C3AED";
const DARK = "#111827";
const GRAY = "#6b7280";
const GREEN = "#22c55e";

export function generateReceiptPdf(data: {
  receiptNumber: string;
  invoiceNumber: string;
  clientName: string;
  clientCompany?: string | null;
  description: string;
  amount: number;
  currency: string;
  date: string;
  runningBalance: number;
}): Buffer {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(24);
  doc.setTextColor(PURPLE);
  doc.text("LeadscoreAI", 20, 30);

  doc.setFontSize(28);
  doc.setTextColor(DARK);
  doc.text("RECEIPT", 190, 30, { align: "right" });

  // Divider
  doc.setDrawColor(PURPLE);
  doc.setLineWidth(0.5);
  doc.line(20, 38, 190, 38);

  // Receipt details
  doc.setFontSize(10);
  doc.setTextColor(GRAY);

  let y = 50;

  const addRow = (label: string, value: string, valueColor: string = DARK) => {
    doc.setTextColor(GRAY);
    doc.text(label, 20, y);
    doc.setTextColor(valueColor);
    doc.setFont("helvetica", "bold");
    doc.text(value, 190, y, { align: "right" });
    doc.setFont("helvetica", "normal");
    y += 10;
  };

  addRow("Receipt #", data.receiptNumber);
  addRow("Invoice #", data.invoiceNumber);
  addRow("Client", data.clientName);
  if (data.clientCompany) {
    addRow("Company", data.clientCompany);
  }
  addRow("Description", data.description);
  addRow("Amount Paid", formatCurrency(data.amount, data.currency), PURPLE);
  addRow("Payment Date", formatDate(data.date));

  // Divider
  y += 5;
  doc.setDrawColor("#e5e7eb");
  doc.setLineWidth(0.3);
  doc.line(20, y, 190, y);
  y += 10;

  addRow("Running Balance", formatCurrency(data.runningBalance, data.currency));

  // Footer
  y += 20;
  doc.setFontSize(9);
  doc.setTextColor(GRAY);
  doc.text("This receipt was generated by LeadscoreAI.", 105, y, { align: "center" });

  return Buffer.from(doc.output("arraybuffer"));
}

export function generateInvoicePdf(invoice: Invoice, client: InvoiceClient): Buffer {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(24);
  doc.setTextColor(PURPLE);
  doc.text("LeadscoreAI", 20, 25);

  doc.setFontSize(28);
  doc.setTextColor(DARK);
  doc.text("INVOICE", 190, 25, { align: "right" });

  // Status badge
  doc.setFontSize(10);
  const statusColors: Record<string, string> = {
    draft: "#6b7280",
    sent: "#3b82f6",
    paid: "#22c55e",
    overdue: "#ef4444",
  };
  doc.setTextColor(statusColors[invoice.status] || GRAY);
  doc.text(invoice.status.toUpperCase(), 190, 33, { align: "right" });

  // Divider
  doc.setDrawColor(PURPLE);
  doc.setLineWidth(0.5);
  doc.line(20, 37, 190, 37);

  // Invoice meta
  let y = 48;
  doc.setFontSize(9);
  doc.setTextColor(GRAY);
  doc.text("Invoice #", 20, y);
  doc.text("Issue Date", 80, y);
  doc.text("Due Date", 140, y);
  y += 6;
  doc.setFontSize(11);
  doc.setTextColor(DARK);
  doc.setFont("helvetica", "bold");
  doc.text(invoice.invoice_number, 20, y);
  doc.text(formatDate(invoice.issue_date), 80, y);
  doc.text(formatDate(invoice.due_date), 140, y);
  doc.setFont("helvetica", "normal");

  // Client
  y += 14;
  doc.setFontSize(9);
  doc.setTextColor(GRAY);
  doc.text("Bill To", 20, y);
  y += 6;
  doc.setFontSize(11);
  doc.setTextColor(DARK);
  doc.setFont("helvetica", "bold");
  doc.text(client.name, 20, y);
  doc.setFont("helvetica", "normal");
  y += 5;
  if (client.company) {
    doc.setFontSize(10);
    doc.setTextColor(GRAY);
    doc.text(client.company, 20, y);
    y += 5;
  }
  doc.setFontSize(10);
  doc.setTextColor(GRAY);
  doc.text(client.email, 20, y);
  y += 10;

  // Line items - charges
  const charges = invoice.line_items.filter((item) => !item.type || item.type === "charge");
  const payments = invoice.line_items.filter((item) => item.type === "payment");
  const hasPayments = payments.length > 0;

  const chargeTableBody = charges.map((item) => [
    item.description + (item.paid ? " (Paid)" : ""),
    String(item.quantity),
    formatCurrency(item.unit_price, invoice.currency),
    formatCurrency(item.amount, invoice.currency),
  ]);

  autoTable(doc, {
    startY: y,
    head: [["Description", "Qty", "Rate", "Amount"]],
    body: chargeTableBody,
    theme: "plain",
    headStyles: {
      fillColor: [124, 58, 237],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    bodyStyles: {
      fontSize: 10,
      textColor: [17, 24, 39],
    },
    columnStyles: {
      0: { cellWidth: 80 },
      1: { halign: "center", cellWidth: 20 },
      2: { halign: "right", cellWidth: 35 },
      3: { halign: "right", cellWidth: 35 },
    },
    margin: { left: 20, right: 20 },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 5;

  // Payments table
  if (hasPayments) {
    doc.setFontSize(9);
    doc.setTextColor(GRAY);
    doc.text("PAYMENTS / DEDUCTIONS", 20, y);
    y += 4;

    const paymentTableBody = payments.map((item) => [
      item.description,
      String(item.quantity),
      formatCurrency(item.unit_price, invoice.currency),
      `-${formatCurrency(item.amount, invoice.currency)}`,
    ]);

    autoTable(doc, {
      startY: y,
      body: paymentTableBody,
      theme: "plain",
      bodyStyles: {
        fontSize: 10,
        textColor: [34, 197, 94],
      },
      columnStyles: {
        0: { cellWidth: 80 },
        1: { halign: "center", cellWidth: 20 },
        2: { halign: "right", cellWidth: 35 },
        3: { halign: "right", cellWidth: 35 },
      },
      margin: { left: 20, right: 20 },
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 5;
  }

  // Totals
  doc.setDrawColor(PURPLE);
  doc.setLineWidth(0.3);
  doc.line(120, y, 190, y);
  y += 8;

  if (hasPayments) {
    const totalCharges = calculateTotalCharges(invoice.line_items);
    const totalPaymentsAmt = calculateTotalPayments(invoice.line_items);
    const balanceDue = calculateBalanceDue(invoice.line_items);

    doc.setFontSize(10);
    doc.setTextColor(GRAY);
    doc.text("Subtotal (Charges)", 120, y);
    doc.setTextColor(DARK);
    doc.text(formatCurrency(totalCharges, invoice.currency), 190, y, { align: "right" });
    y += 7;

    doc.setTextColor(GREEN);
    doc.text("Payments", 120, y);
    doc.text(`-${formatCurrency(totalPaymentsAmt, invoice.currency)}`, 190, y, { align: "right" });
    y += 7;

    doc.setFontSize(12);
    doc.setTextColor(PURPLE);
    doc.setFont("helvetica", "bold");
    doc.text("Balance Due", 120, y);
    doc.text(formatCurrency(balanceDue, invoice.currency), 190, y, { align: "right" });
    doc.setFont("helvetica", "normal");
  } else {
    doc.setFontSize(12);
    doc.setTextColor(GRAY);
    doc.text("Total", 120, y);
    doc.setTextColor(PURPLE);
    doc.setFont("helvetica", "bold");
    doc.text(formatCurrency(invoice.subtotal, invoice.currency), 190, y, { align: "right" });
    doc.setFont("helvetica", "normal");
  }

  y += 15;

  // Bank details
  const bank = invoice.bank_details;
  if (bank && Object.keys(bank).length > 0) {
    doc.setFontSize(9);
    doc.setTextColor(GRAY);
    doc.text("PAYMENT DETAILS", 20, y);
    y += 6;

    doc.setFontSize(10);
    const bankFields: [string, string | undefined][] = [
      ["Bank", bank.bank_name],
      ["Account Name", bank.account_name],
      ["Account Number", bank.account_number],
      ["Sort Code", bank.sort_code],
      ["IBAN", bank.iban],
      ["SWIFT", bank.swift],
    ];

    for (const [label, value] of bankFields) {
      if (!value) continue;
      doc.setTextColor(GRAY);
      doc.text(`${label}:`, 20, y);
      doc.setTextColor(DARK);
      doc.text(value, 65, y);
      y += 6;
    }

    y += 5;
  }

  // Notes
  if (invoice.notes) {
    doc.setFontSize(9);
    doc.setTextColor(GRAY);
    doc.text("NOTES", 20, y);
    y += 6;
    doc.setFontSize(10);
    doc.setTextColor(GRAY);
    const splitNotes = doc.splitTextToSize(invoice.notes, 170);
    doc.text(splitNotes, 20, y);
    y += splitNotes.length * 5 + 5;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(GRAY);
  doc.text("This invoice was generated by LeadscoreAI.", 105, 285, { align: "center" });

  return Buffer.from(doc.output("arraybuffer"));
}
